### ISSUE TITLE
Locals are gateway to desyncs

### ISSUE THREAD

**Issue by Adilf** [sirenfal-factorio/Free_Real_Estate#2]
It seems that you have a local variable in the code, that is allowed to be changed during the execution on the line 128 of control.lua.

I didn't get the desync from that, but someone else probably might.

**Comment by avosirenfal** [comment]
Good eyes. I meant to refactor this but forgot to write it down and never looked at it again. I didn't notice because it's an extremely rare fail case. Should be fixed now.

Thanks for the report.

**Comment by avosirenfal** [comment]
Have you had a chance to try it any more?
