### ISSUE TITLE
Bugs when link two building side-by-side with item relay

### ISSUE THREAD

**Issue by yumeyuu** [sirenfal-factorio/Free_Real_Estate#8]
There seems to be a bug when updating item relay stack limits on the code in "/factory/input_relays/items.lua" (in line 155 or line 156). There seems to be a case when one of the data (either self.input or self. output) will end up on null, then when the function tries to access its member via get_inventory the function will throws an error stating the data is null

![setup](https://cloud.githubusercontent.com/assets/26128089/24070986/40f6cbc2-0bfa-11e7-9352-c69e6178ac07.jpg)

![error](https://cloud.githubusercontent.com/assets/26128089/24070989/4cbee552-0bfa-11e7-89d0-15ff2349ebc3.jpg)

the code:
```lua
for _, inven in pairs({
    self.input.get_inventory(defines.inventory.chest),
    self.output.get_inventory(defines.inventory.chest),
}) do
    local slots = #inven

    if (free_real_estate.config.item_relay_bar < slots) then
        inven.setbar(free_real_estate.config.item_relay_bar)
    end
end
```

I tried to fix it by adding extra check on the code:
```lua
local cinven
if (self.input ~= nil and self.output ~= nil) then
    cinven = {
        self.input.get_inventory(defines.inventory.chest) ,
        self.output.get_inventory(defines.inventory.chest) ,
        }
else
    cinven = { (self.input or self.output).get_inventory(defines.inventory.chest) }
end

for _, inven in pairs(cinven) do
    local slots = #inven

    if (free_real_estate.config.item_relay_bar < slots) then
        inven.setbar(free_real_estate.config.item_relay_bar)
    end
end
```

which seems to fix the error

**Comment by avosirenfal** [comment]
This should be fixed in 1.0.6. Please let me know if you run into any other issues :)
