### ISSUE TITLE
Empty factory crashes on pickup / destroy. v1.0.6

### ISSUE THREAD

**Issue by shadoskill** [sirenfal-factorio/Free_Real_Estate#9]
We have left a factory that was completely empty for a few days it was in the way, tried to break it and the server crashed, tested multiple times. Shooting it to destroy it also crashed the server.
Edit: All factories seem to be doing this now.
> Popup error:
> Error while running even on_player_mined_item(ID 11)
> _ _Free_Real_Estate_ _/factory/waypoint.lua:104: attempted to index a nil value

[save5.zip](https://github.com/sirenfal-factorio/Free_Real_Estate/files/852817/save5.zip)
Mods: https://mega.nz/#!JEFUWCQB!a4tIK-90Ui_C4_0mGUeiJ1EnqxX2r_mnQ5tHfRThf6c

**Comment by avosirenfal** [comment]
This should be fixed in 1.0.7. Let me know if you have any other problems :)
